/*
 * generated by Xtext
 */
package edu.unq.obj3.ui.contentassist

import edu.unq.obj3.ui.contentassist.AbstractFobalClaseProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FobalClaseProposalProvider extends AbstractFobalClaseProposalProvider {
}
