/*
 * generated by Xtext
 */
package edu.unq.obj3.validation

import edu.unq.obj3.fobalClase.Campeonato
import edu.unq.obj3.fobalClase.Equipo
import java.util.List
import org.eclipse.xtext.validation.Check
import edu.unq.obj3.fobalClase.FobalClasePackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class FobalClaseValidator extends AbstractFobalClaseValidator {

	@Check
	def checkNombreEquipoLargo(Equipo equipo) {
		if (equipo.name.length < 2) {
			error(
				"Pone al menos dos letras, zangano", 
				equipo,
				null)
		}
	}

	@Check
	def checkNombreEquipoNoRepetido(Campeonato camp) {
		val List<String> nombres = newArrayList()
		camp.equipos.forEach[ equipo |
			if (nombres.contains(equipo.name))
				// error
				error("El nombre esta repetido", 
					equipo, 
					equipo.eClass.getEStructuralFeature(
						FobalClasePackage.EQUIPO__NAME
					)
				)
			else
				nombres.add(equipo.name)
		] 
	}
	
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
