/*
 * generated by Xtext
 */
package edu.unq.obj3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FobalClaseUiModule extends edu.unq.obj3.ui.AbstractFobalClaseUiModule {
	public FobalClaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
