/*
 * generated by Xtext
 */
package edu.unq.obj3;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FobalClaseRuntimeModule extends edu.unq.obj3.AbstractFobalClaseRuntimeModule {

}
