/*
* generated by Xtext
*/
package edu.unq.obj3;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FobalClaseStandaloneSetup extends FobalClaseStandaloneSetupGenerated{

	public static void doSetup() {
		new FobalClaseStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

